include:
  - infra.yaml
services:
  auth-service:
    image: auth-service:latest
    ports:
      - "50052:50052"
      - "8080:8080"
    restart: unless-stopped
    env_file: "auth-service.env"
    depends_on:
      - pg
